[package]
name = "cloudflare-examples"
version = "0.5.0"
edition = "2018"
description = "Examples of how to use the Cloudflare Rust API client"

[[bin]]
name = "cloudflare-examples"
path = "src/main.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33"
cloudflare = {path = "../cloudflare"}
failure = "0.1.5"
maplit = "1.0"
serde = { version = "1.0" }
serde_json = "1.0"