[package]
name = "cloudflare"
version = "0.8.3"
authors = ["Areg Harutyunyan <areg@cloudflare.com>"]
edition = "2018"
description = "Rust library for the Cloudflare v4 API"
keywords = ["cloudflare", "api", "client"]
categories = ["api-bindings", "web-programming::http-client"]
license = "BSD-3-Clause"

[features]
default = ["request"]
request = ["url"]

[dependencies]
async-trait = { version = "0.1", optional = true }
base64 = "0.13"
chrono = { version = "0.4", default-features = false, features = ["serde"] }
http = "0.2"
percent-encoding = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "1.8"
url = { version = "2.2", optional = true }